#!/bin/sh

# Taken from voidrice: https://github.com/LukeSmithxyz/voidrice
# This script is the SUDO_ASKPASS variable, meaning that it will be used as a
# password prompt if needed.

dmenu -fn Monospace-18 -P -p "$1" <&- && echo
